### ISSUE TITLE
Particle system

### ISSUE THREAD

**Issue by XenoMustache** [XenoMustache/far-beyond-legacy#10]
Particles will be used for many different things. They will be required to render the asteroids in the asteroid hazard, as well as a new damage indicator for ships.  

**TODO**
- [ ] Dynamic particles for ship damage
- [ ] Explosion particle effect for ship destruction
- [ ] FTL particle effect for ship spawn
