### ISSUE TITLE
Rework NPCs

### ISSUE THREAD

**Issue by XenoMustache** [XenoMustache/far-beyond-legacy#14]
The AI used for both pirates and civilians is pretty clunky and contains tons of unused and broken code. An entire rework of the AI is required to amend these shortcomings. Additionally, the NPCs do not move like the player at all with the changes made to the movement, improvements will be made so that the movement more closely matches each other.

**TODO**
- [ ] Removed all unused / broken code
- [ ] General AI improvements, such as additional states (e.g. civilians flee pirates)
- [ ] Improve NPC movement to match player movement
- [ ] NPCs interact with hazards
