### ISSUE TITLE
UI and UX changes and additions

### ISSUE THREAD

**Issue by XenoMustache** [XenoMustache/far-beyond-legacy#15]
The interface and experience designs of the game are currently pretty lacking and leave much to be desired. Currently the state of the game feels like a clunky mess, and the style of the interface reinforces that feeling. For now let's focus on basic improvements which will be expanded later on.

**TODO**
- [x] Animated message box open and close
- [x] Animated buttons when created and destroyed
- [ ] Better button color blending and animation on hover
