### ISSUE TITLE
Major changes to gameplay

### ISSUE THREAD

**Issue by XenoMustache** [XenoMustache/far-beyond-legacy#18]
Several changes to the way the game plays will need to be made to many different parts of the game.

**TODO**
- [ ] Changes to pace
- [ ] Changes to enemy handling
- [ ] Placeholder story for pre-alpha, to be adapted, changed, or expanded after pre-alpha

Will add more soon
