### ISSUE TITLE
Ingame changelog and markdown file converter

### ISSUE THREAD

**Issue by XenoMustache** [XenoMustache/far-beyond-legacy#2]
The title screen will feature an ingame changelog which will replace the readme file which is included with each release. This changelog will include all logs in every previous release, and the current release. 

This changelog will be generated from a markdown file. This file will be translated and rendered to the game's screen in the form of a surface, which can be scrolled up and down indefinitely. 

**TODO**
- [ ] Changelog interface is present within the title screen of the game
- [ ] Changelog renders onto a surface which can be scrolled up and down
- [ ] Changelog reads a markdown file included with the projects and converts is into formatted readable text.
- [ ] Changelog contains all information relating to changes in the project, past and present.
