### ISSUE TITLE
Rework attack system to include dynamic damage and critical hits

### ISSUE THREAD

**Issue by XenoMustache** [XenoMustache/far-beyond-legacy#3]
All attack types should do varying damage within a range based on what attacks they are and what object they come from. There should also be a chance and modifier value for how much damage a critical attack will do and how often these occur.

**TODO**
- [ ] Attacks should be based on a min and max range of damage a basic attack does
- [ ] Attacks should have a chance value for frequency of crits
- [ ] Crits should be based on a modifier value which modifies the damage the crit does to a target
