### ISSUE TITLE
Asteroid field

### ISSUE THREAD

**Issue by XenoMustache** [XenoMustache/far-beyond-legacy#6]
Hazard objects are zones and areas of a map which define a clear danger to the player. This can range from varying things, and have various effects on the player (e.g. health loss overtime). This issues relates to the asteroid field hazard effect in particular.

Asteroid hazards must have a defined zone. They must be reversible to affect only certain areas, or all areas aside from where they are. They must have a render effect including asteroid particle effects floating within the hazard area.

**TODO**
- [x] Asteroids have defined zone
- [x] Asteroid field can be reversed
- [x] Player takes damage over time when inside asteroid field
- [ ] Asteroid field renders its effect
