### ISSUE TITLE
Pause and settings menu

### ISSUE THREAD

**Issue by XenoMustache** [XenoMustache/far-beyond-legacy#7]
The settings and pause menus will each play their own roles in user interaction with the game. The pause menu will allow the player to edit settings and leave the game as they see fit, as well as return to the menu. The settings menu will allow users to tweak various things about the game. These menus will be totally redesigned from past iterations.  

**TODO**
- [ ] Pause menu should appear when game is paused. 
- [ ] Settings menu can be accessed through the title screen and pause menu
- [ ] Quickpause (space key) is unaffected by the addition of the pause menu.
- [ ] Settings menu is divided into four sub menus, gameplay, video, audio and misc
- [ ] Each submenus have their own categories for different types of settings (eg screen resolution vs graphical optimization settings)
- [ ] The settings menu can correctly edit the settings file which is generated and loaded by the game at runtim
